theme: jekyll-theme-dinky
title: Introduction to Statistical Computing (STATS 306), Winter 2021
description: Welcome to Ryan’s lab page! Here, you’ll find everything you need for our weekly lab.
github:
  is_project_page: false
