theme: jekyll-theme-dinky
title: Introduction to Statistical Computing, Winter 2021
description: Welcome to Ryan’s lab page! Here, you’ll find all materials for our weekly lab.
github:
  is_project_page: false
